# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPzih7VJmx86Espdbjzghw0f3YfBvvor
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy import stats as sps
import seaborn as sns

data = pd.read_csv('/content/ab_stats.csv')

data.head()

data.describe()

count_A = data[data['ab_group']=='A']['ab_group'].count()
count_A

count_B = data[data['ab_group']=='B']['ab_group'].count()
count_B

"""Количество пользователей в двух группах значимо не отличается

Рассчитываем ARPPU для каждой группы
"""

paying_users_A = data[(data['ab_group'] == 'A') & (data['num_purchases'] > 0)]
paying_users_B = data[(data['ab_group'] == 'B') & (data['num_purchases'] > 0)]
total_revenue_A = paying_users_A['revenue'].sum()
total_revenue_B = paying_users_B['revenue'].sum()
num_paying_users_A = len(paying_users_A)
num_paying_users_B = len(paying_users_B)
ARPPU_A = total_revenue_A / num_paying_users_A if num_paying_users_A > 0 else 0
ARPPU_B = total_revenue_B / num_paying_users_B if num_paying_users_B > 0 else 0
ARPPU_A, ARPPU_B

revenue_A = np.array(data[
    (data['ab_group']=='A') &
     (data['purchase']==1)
     ]['revenue'])
revenue_B = np.array(data[
    (data['ab_group']=='B') &
     (data['purchase']==1)
     ]['revenue'])

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8, 4))
sns.histplot(paying_users_A['revenue'], color="blue", label="Группа A", kde=True)
sns.histplot(paying_users_B['revenue'], color="red", label="Группа B", kde=True)
plt.title('Распределение дохода среди платящих пользователей')
plt.xlabel('Доход')
plt.ylabel('Частота')
plt.legend()
plt.show()

from scipy.stats import mannwhitneyu
stat, p_value = mannwhitneyu(paying_users_A['revenue'], paying_users_B['revenue'], alternative='two-sided')
p_value

"""Тест Манна-Уитни говорит о том, что значимых различий между группами нет, так как pvalue=0.88, что гораздо больше 5%-го уровня значимости, и тем более 1%-го.

Учитывая вышесказанное, нет необходимости применять альтернативный вариант, тестируемый в группе В, и оставить текущий вариант А.

Рекомендация:

Провести анализ других метрик или факторов, которые могут оказывать влияние на доходы. Например, рассмотреть влияние различных категорий пользователей или типов продуктов на доход, с последующим проведение A/B тестов.
"""